backend:
  name: git-gateway
  repo: dongleizhang/blog
  branch: hexo-source # Branch to update (master by default)

media_folder: "source/assets" # Folder path where uploaded files should be saved, relative to the base of the repo.
public_folder: "/assets" # Folder path where uploaded files will be accessed, relative to the base of the built site.

publish_mode: editorial_workflow
site_url: https://blog.dlzhang.com
display_url: https://blog.dlzhang.com
logo_url: /img/logo.svg
show_preview_links: true
# slug:
#   encoding: "ascii" # default: unicode
#   clean_accents: true
#   sanitize_replacement: "_"  # default: "-"


collections: # A list of collections the CMS should be able to edit
  - name: "bookmovie" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "书影新世界" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/书影新世界" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["「书影新世界」"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "academic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "学术不神秘" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/学术不神秘" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["「学术不神秘」"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "technology" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "技术三两事" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/技术三两事" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["「技术三两事」"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "notes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "生活随手记" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/生活随手记" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["「生活随手记」"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "ramble" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "碎碎念不停" # Used in the UI, ie.: "New Post"
    folder: "/source/_posts/碎碎念不停" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "标题", name: "title", widget: "string"}
      - {label: "专栏", name: "categories", widget: "list", default: ["「碎碎念不停」"]}
      - {label: "标签", name: "tags", widget: "list", default: [""]}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "置顶", name: "top", widget: "boolean", default: false}
      - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
      - {label: "LaTex", name: "mathjax", widget: "boolean", default: false}
      - {label: "评论", name: "comments", widget: "boolean", default: true}
      - {label: "赞赏", name: "reward", widget: "boolean", default: true}
      - {label: "永久链接", name: "abbrlink", widget: "string", default: "", required: false}
      - {label: "正文", name: "body", widget: "markdown", default: "<!-- more -->"}
  - name: "pages"
    label: "页面设置"
    files:
      - name: "about"
        label: "关于班班"
        file: "/source/about/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "404"
        label: "404 页面"
        file: "/source/404/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "侧边目录", name: "toc", widget: "boolean", default: false}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "永久链接", name: "permalink", widget: "string", default: "/404"}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "photos"
        label: "光影留痕"
        file: "/source/photos/index.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "类型", name: "type", widget: "string", default: "picture"}
          - {label: "评论", name: "comments", widget: "boolean", default: true}
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "readme_hexo"
        label: "README (hexo-source)"
        file: "/source/README.md"
        fields:
          - {label: "正文", name: "body", widget: "markdown"}
      - name: "readme_master"
        label: "README (master)"
        file: "/README.md"
        fields:
          - {label: "正文", name: "body", widget: "markdown"}